#!/usr/bin/env bash

SYSTEM_TYPE=$(uname -s)

#-----------------------------------------
# * Install brew packages and casks
#   https://yadm.io/docs/bootstrap
#-----------------------------------------

if [ "$SYSTEM_TYPE" = "Darwin" ]; then

  echo "Installing brew packages..."
  brew bundle --file=~/.brew/Brewfile.base

fi

